services:
  - type: web
    name: vw-stock-lstm-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 300 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free
